### ISSUE TITLE
Error in multi-window resize app

### ISSUE THREAD

**Issue by webserveis** [KingJA/LoadSir#115]
- If rotated the device works well
- If I put the app in multi-window it works well
- If rotate the device with two apps in windows, works well
- When resizing the app, ERROR

My code in Activity

```
mRecyclerView = findViewById(R.id.list_result);
initRecyclerView();

 loadService = LoadSir.getDefault().register(mRecyclerView); //error when strech in multi-view
```
Log error

>    Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.webserveis.basewebtool/com.webserveis.basewebtool.ReportActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4950)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5161)
        at android.view.ViewGroup.addView(ViewGroup.java:4991)
        at android.view.ViewGroup.addView(ViewGroup.java:4931)
        at android.view.ViewGroup.addView(ViewGroup.java:4904)
        at com.kingja.loadsir.core.LoadLayout.setupSuccessLayout(LoadLayout.java:44)
        at com.kingja.loadsir.core.LoadService.<init>(LoadService.java:30)
        at com.kingja.loadsir.core.LoadSir.register(LoadSir.java:55)
        at com.kingja.loadsir.core.LoadSir.register(LoadSir.java:45)
        at com.webserveis.basewebtool.ReportActivity.onCreate(ReportActivity.java:65)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4950) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1730) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7000) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 

**Work fine with**

   loadService = LoadSir.getDefault().register(this);

and

 loadService = LoadSir.getDefault().register(android.R.id.content);

But no use RecyclerView how to view

**Comment by KingJA** [comment]
@webserveis Hi gay, tks for your reply, I will check.  It will be helpful if you could provide the sample the exception happened,  BTW, 1.3.8 is available now  :)
