### ISSUE TITLE
两层constraintlayout，以内层的constraintlayout为targetview在我们项目中报错

### ISSUE THREAD

**Issue by supercodeing** [KingJA/LoadSir#128]
报错信息是说Framealayout.layoutparams不能强转成ConstraintLayout.layoutparams
但是按照loadersir的思路我写了个demo也是两层Constraintlayout,没有报错正常运行。想知道是不是loadsir还是不能支持ConstraintLayout?如果不支持为什么有的情况下与constraintLayout结合可以使用。具体哪些情况不能用呢
报错信息：
java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams
        at androidx.constraintlayout.widget.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
        at androidx.constraintlayout.widget.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:1038)
        at androidx.constraintlayout.widget.ConstraintLayout.updateHierarchy(ConstraintLayout.java:803)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1561)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
        at android.view.View.measure(View.java:23466)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by supercodeing** [comment]
我用的就是1.3.8loadsir。 androidx.constraintlayout.widget.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
getTargetWidget()源码中确实在这个地方强转成constraintLayout.layoutparams类型。不过不知道报错中强转的这个view到底是谁？

**Comment by KingJA** [comment]
@dongbaoming123 你好，如果注册的View是其它元素的约束对象就有可能报这样的错误，这个时候最好在该View外层包一层父布局(Ll,Rl,Fl都行)，把其它对象的约束id转移到这个父布局上，如果没被其它元素约束，就OK，如果还有疑问继续留言。

**Comment by supercodeing** [comment]
targetview是其它元素的约束对象。这样说太笼统，我记得我是尝试外面加了一层framelayout，把约束转移到了framelayout上面，但是还是不行，报同样的错误，几经尝试不行所以才来提问？能不能具体一点呢，什么样才算是成了其它元素的约束对象？后续我会再试一下外面加一层framelayout。

**Comment by supercodeing** [comment]
这是我之前加的一层framelayout,回头我再尝试一下免得有细节做错。
 <FrameLayout
            android:id="@+id/content_container"
            android:layout_width="match_parent"
            android:layout_height="0pt"
            android:layout_marginTop="@dimen/distance_10"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toBottomOf="@id/title"
            app:layout_constraintVertical_weight="1">


            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/content"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/left_recyclerview"
                    android:layout_width="0pt"
                    android:layout_height="match_parent"
                    android:background="@color/light_gray_ec"
                    app:layout_constraintEnd_toStartOf="@+id/right_recyclerview"
                    app:layout_constraintHorizontal_weight="112"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:listitem="@layout/left_department_item_layout" />

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/right_recyclerview"
                    android:layout_width="0pt"
                    android:layout_height="match_parent"
                    android:background="@color/white"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintHorizontal_weight="263"
                    app:layout_constraintStart_toEndOf="@+id/left_recyclerview"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:listitem="@layout/right_department_item_layout" />

            </androidx.constraintlayout.widget.ConstraintLayout>
        </FrameLayout>
一般的，targetview有一些约束属性也能正常使用loadsir的。我这个是不是因为比其他一般情况多了weight约束所以才不能成功？还是想具体知道约束布局里哪些情况能用哪些不能，不能用的原理能给讲下不？看代码Layoutparams还是用的targetview的，不该出现强转失败异常啊

**Comment by dongbaoming123** [comment]
<FrameLayout
            android:id="@+id/content_container"
            android:layout_width="match_parent"
            android:layout_height="0pt"
            android:layout_marginTop="@dimen/distance_10"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintTop_toBottomOf="@id/title"
            app:layout_constraintVertical_weight="1">


            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/content"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/left_recyclerview"
                    android:layout_width="0pt"
                    android:layout_height="match_parent"
                    android:background="@color/light_gray_ec"
                    app:layout_constraintEnd_toStartOf="@+id/right_recyclerview"
                    app:layout_constraintHorizontal_weight="112"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:listitem="@layout/left_department_item_layout" />

                <androidx.recyclerview.widget.RecyclerView
                    android:id="@+id/right_recyclerview"
                    android:layout_width="0pt"
                    android:layout_height="match_parent"
                    android:background="@color/white"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintHorizontal_weight="263"
                    app:layout_constraintStart_toEndOf="@+id/left_recyclerview"
                    app:layout_constraintTop_toTopOf="parent"
                    tools:listitem="@layout/right_department_item_layout" />

            </androidx.constraintlayout.widget.ConstraintLayout>
</FrameLayout>
上一层代码粘错了

**Comment by KingJA** [comment]
@dongbaoming123 你好，我建了个QQ群(818251143)，方便的话加入，沟通会方便点

**Comment by MuXIaoHong** [comment]
> 我用的就是1.3.8loadsir。 androidx.constraintlayout.widget.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
> getTargetWidget()源码中确实在这个地方强转成constraintLayout.layoutparams类型。不过不知道报错中强转的这个view到底是谁？



> 报错信息是说Framealayout.layoutparams不能强转成ConstraintLayout.layoutparams
> 但是按照loadersir的思路我写了个demo也是两层Constraintlayout,没有报错正常运行。想知道是不是loadsir还是不能支持ConstraintLayout?如果不支持为什么有的情况下与constraintLayout结合可以使用。具体哪些情况不能用呢
> 报错信息：
> java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to androidx.constraintlayout.widget.ConstraintLayout$LayoutParams
> at androidx.constraintlayout.widget.ConstraintLayout.getTargetWidget(ConstraintLayout.java:1144)
> at androidx.constraintlayout.widget.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:1038)
> at androidx.constraintlayout.widget.ConstraintLayout.updateHierarchy(ConstraintLayout.java:803)
> at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1561)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
> at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1565)
> at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
> at android.widget.LinearLayout.onMeasure(LinearLayout.java:726)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
> at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
> at com.android.internal.policy.DecorView.onMeasure(DecorView.java:847)
> at android.view.View.measure(View.java:23466)
> at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2954)
> at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1753)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2041)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
> at android.view.Choreographer.doCallbacks(Choreographer.java:893)
> at android.view.Choreographer.doFrame(Choreographer.java:812)
> at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
> at android.os.Handler.handleCallback(Handler.java:907)
> at android.os.Handler.dispatchMessage(Handler.java:105)
> at android.os.Looper.loop(Looper.java:216)
> at android.app.ActivityThread.main(ActivityThread.java:7625)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

哈喽 这个问题解决了没

**Comment by KingJA** [comment]
@MuXIaoHong 你好，方便的话加群聊QQ群(818251143)
