### ISSUE TITLE
App后台放置一段时间 再打开会崩溃报错

### ISSUE THREAD

**Issue by NeVaDaAAA** [KingJA/LoadSir#142]
注册方式使用的是APP中注册 BaseActivity/Basefragment中做了个性化需求 
代码如下:
loadService = LoadSir.getDefault().register(view) {
            // 重新加载逻辑
            if (loadService.currentCallback == ErrorCallback::class.java) {
                if (isNeedErrLoading) {
                    loadService.showCallback(LoadingCallback::class.java)
                }
                this@BaseActivity.loadErrorClick()
            }
        }

报错信息如下:
Device : Xiaomi MIX 2S 
OS version : Android 10 (SDK 29) 
 
Stack trace :  
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.petshub.pethelper/com.yinxing.information.mine.ui.activity.PersonActivity}: java.lang.IllegalArgumentException: The Callback (ErrorCallback) is nonexistent.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3313)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2049)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
Caused by: java.lang.IllegalArgumentException: The Callback (ErrorCallback) is nonexistent.
	at com.kingja.loadsir.core.LoadLayout.checkCallbackExist(LoadLayout.java:124)
	at com.kingja.loadsir.core.LoadLayout.setCallBack(LoadLayout.java:118)
	at com.kingja.loadsir.core.LoadService.setCallBack(LoadService.java:99)
	at com.yinxing.pethelper.base.BaseActivity.initLoadSir(BaseActivity.kt:138)
	at com.yinxing.pethelper.base.BaseActivity.initLoadSir$default(BaseActivity.kt:127)
	at com.yinxing.information.mine.ui.activity.PersonActivity.initView(PersonActivity.kt:134)
	at com.yinxing.pethelper.base.BaseActivity.onCreate(BaseActivity.kt:63)
	at android.app.Activity.performCreate(Activity.java:7893)
	at android.app.Activity.performCreate(Activity.java:7880)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3288)

**Comment by KingJA** [comment]
@NeVaDaAAA 请提供初始化的代码

**Comment by loflv** [comment]
public class LoadSir {
    private static volatile LoadSir loadSir;
    private Builder builder;
}
builder不是静态的，导致在后台时builder里面保存的callback被清除了，应该是这个原因
