### ISSUE TITLE
viewpager和fragement,fragement下嵌套子fragment会报这个错

### ISSUE THREAD

**Issue by Whdsk** [KingJA/LoadSir#88]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4455)
        at android.view.ViewGroup.addView(ViewGroup.java:4291)
        at android.view.ViewGroup.addView(ViewGroup.java:4232)
        at android.view.ViewGroup.addView(ViewGroup.java:4205)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2276)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:19376)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1744)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:805)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:665)
        at android.view.View.measure(View.java:19376)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1744)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:805)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:665)
        at android.view.View.measure(View.java:19376)
        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
        at android.view.View.measure(View.java:19376)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1744)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:805)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:665)
        at android.view.View.measure(View.java:19376)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
        at android.view.View.measure(View.java:19376)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6138)

**Comment by KingJA** [comment]
@Whdsk 你好，我怀疑你是使用了错误的生命周期方法来创建LoadService，请参考demo中Fragment+ViewPager的案例。

**Comment by Whdsk** [comment]
嗯，好的，谢谢
