### ISSUE TITLE
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by qq61821191** [KingJA/LoadSir#91]
我的是MainActivity，使用FrameLayout+RadioGroup的菜单。
我在BaseFragment中，封装LoadSir
具体代码：
public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view=inflater.inflate(attachLayoutId(), container, false);
        ButterKnife.bind(this,view);
        llContent=(LinearLayout)view.findViewById(R.id.ll_content);
        if(llContent!=null){
            mLoadService= LoadSir.getDefault().register(llContent, new Callback.OnReloadListener() {
                @Override
                public void onReload(View v) {
                    onNetReload(v);
                }
            });
        }else{
            mLoadService=LoadSir.getDefault().register(view, new Callback.OnReloadListener() {
                @Override
                public void onReload(View v) {
                    onNetReload(v);
                }
            });
        }
        initView(view,savedInstanceState);
        mLoadService.showSuccess();
        return mLoadService.getLoadLayout();
    }

MainActivity中四个菜单  第一个Fragment中有三个子fragment没问题，第二个Fragment有四个子Fragment也没问题，第三个只有一个Fragment的则报错。错误日志：
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                              at android.view.ViewGroup.addViewInner(ViewGroup.java:4454)
                                                                              at android.view.ViewGroup.addView(ViewGroup.java:4295)
                                                                              at android.view.ViewGroup.addView(ViewGroup.java:4235)
                                                                              at android.view.ViewGroup.addView(ViewGroup.java:4208)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1425)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                              at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                              at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                              at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                              at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                              at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

我把错误的Fragment的ll_content去掉，不报错，但是不显示加载信息。。。加上ll_content则报以上错误，希望有人帮忙解决一下

**Comment by KingJA** [comment]
@qq61821191 你好，如果方便的话请把场景做成DEMO发给我。

**Comment by qq61821191** [comment]
@KingJA 作者你好，我把场景demo放在bd网盘，也发给你github邮箱中，有空的话帮我看看 谢谢~
https://pan.baidu.com/s/19Jbs090xDMNWK6RFG8iRRA

**Comment by qq61821191** [comment]
@KingJA 这个问题处理完毕，有的Fragment写法不一样。目前有出现个新问题。Rxjava网络请求，onSuccess中无法显示empty，在onError中可以显示？

**Comment by qq61821191** [comment]
@KingJA 作者方便的话加下我的QQ，61821191   几个问题想咨询一下

**Comment by daiwenbo88** [comment]
我也碰到这样的问题  好像 activity 在加载fragment 的时候 不能上状态页

**Comment by BryceLee** [comment]
请问这个问题如何解决？

**Comment by BryceLee** [comment]
@qq61821191 @daiwenbo88 @KingJA
